DEFINE SCHEMA_NAME = &&1
DEFINE SCHEMA_PASSWORD = &&2
DEFINE SCHEMA_TBSP = &&3

CREATE USER &&SCHEMA_NAME IDENTIFIED BY &&SCHEMA_PASSWORD
DEFAULT TABLESPACE &&SCHEMA_TBSP
TEMPORARY TABLESPACE TEMP
QUOTA 20M on &&SCHEMA_TBSP;


