SET TIME ON
SET TIMING ON
SET APPINFO ON


PROMPT Username:
DEFINE USER_NAME = &&1
PROMPT Password:
DEFINE SCHEMA_PASSWORD = &&2
PROMPT TBSP location:
DEFINE TBSP_LOCATION =  &&3

 
SPOOL INSTALL_SCHEMA.LOG

SET SERVEROUTPUT ON

PROMPT Your username: &&USER_NAME
PROMPT
PROMPT Your path: &&TBSP_LOCATION
PROMPT 
PROMPT Creating tablespace:


@create_tablespace.sql &&USER_NAME &&TBSP_LOCATION  
PROMPT

PROMPT
PROMPT Creating user
PROMPT

@create_schema.sql &&USER_NAME &&SCHEMA_PASSWORD &&DATA_TBSP_NAME


PROMPT Granting privileges


@grant_privileges.sql &&USER_NAME

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME;
UNDEFINE TBS_LOCATION;
UNDEFINE SCHEMA_PASSWORD;


SPOOL OFF