SET TIME ON
SET TIMING ON

PROMPT Username:
DEFINE USER_NAME = &&1
PROMPT TBSP name:
DEFINE TABLESPACE_NAME = &&2

SPOOL DROP_SCHEMA.LOG

SET SERVEROUTPUT ON
PROMPT Drop username: &&USER_NAME
PROMPT

@drop_schema.sql &&USER_NAME

PROMPT Drop TBSP: &&TABLESPACE_NAME
PROMPT

@drop_tablespace.sql &&TABLESPACE_NAME

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME

SPOOL OFF