
CREATE VIEW result AS 
SELECT 
    USERS.FIRST_NAME USER_FIRST_NAME,
    USERS.LAST_NAME USER_LAST_NAME,
    USERS.NICKNAME USER_NICKNAME,
    USERS.EMAIL,
    PLAYLIST.PLAYLIST_NAME,
    PLAYLIST.PLAYLIST_CREATOR,
    GENRE.GENRE_NAME,
    COMPOSITION.COMPOSITION_NAME,
    COMPOSITION.DURATION,
    COMPOSITION_OWNER.FIRST_NAME OWNER_FIRST_NAME,
    COMPOSITION_OWNER.LAST_NAME OWNER_LAST_NAME,
    COMPOSITION_OWNER.NICKNAME OWNER_NICKNAME,
    COMPOSITION_REVIEW.LIKED,
    COMPOSITION.LIKES_NUMBER,
    COMPOSITION.LISTENINGS_NUMBER,
    COMPOSITION_REVIEW.REVIEW,
    USER_STATE.CURRENT_COMPOSITION,
    USER_STATE.PAUSE_TIME
FROM USERS
join USER_PLAYLIST
on USERS.ID = USER_PLAYLIST.USER_ID
join PLAYLIST
on USER_PLAYLIST.PLAYLIST_ID = PLAYLIST.ID
join USER_STATE
on USERS.ID = USER_STATE.USER_ID
join COMPOSITION
on COMPOSITION.ID = USER_STATE.COMPOSITION_ID
join COMPOSITION_OWNER
on COMPOSITION_OWNER.ID = COMPOSITION.OWNER_ID
join COMPOSITION_REVIEW
on COMPOSITION.ID = COMPOSITION_REVIEW.COMPOSITION_ID
join GENRE
on COMPOSITION.ID = GENRE.COMPOSITION_ID
group by 
   USERS.FIRST_NAME,
   USERS.LAST_NAME,
   USERS.NICKNAME,
    USERS.EMAIL,
    PLAYLIST.PLAYLIST_NAME,
    PLAYLIST.PLAYLIST_CREATOR,
    GENRE.GENRE_NAME,
    COMPOSITION.COMPOSITION_NAME,
    COMPOSITION.DURATION,
    COMPOSITION.LIKES_NUMBER,
    COMPOSITION.LISTENINGS_NUMBER,
    COMPOSITION_OWNER.FIRST_NAME,
    COMPOSITION_OWNER.LAST_NAME,
    COMPOSITION_OWNER.NICKNAME,
    COMPOSITION_REVIEW.REVIEW,
    COMPOSITION_REVIEW.LIKED,
    USER_STATE.CURRENT_COMPOSITION,
    USER_STATE.PAUSE_TIME;