CREATE TABLE DATA_TABLE 
(
  FIRST_NAME VARCHAR2(100) 
, LAST_NAME VARCHAR2(100) 
, NICKNAME VARCHAR2(100) 
, EMAIL VARCHAR2(100) 
, PLAYLIST_NAME VARCHAR2(100) 
, PLAYLIST_TYPE VARCHAR2(6) 
, GENRE VARCHAR2(100) 
, COMPOSITION_NAME VARCHAR2(100) 
, DURATION NUMBER 
, OWNER_FIRST_NAME VARCHAR2(100) 
, OWNER_LAST_NAME VARCHAR2(100) 
, OWNER_NICKNAME VARCHAR2(100)
, LIKED VARCHAR2(3) 
, COMPOSITION_LIKES NUMBER 
, COMPOSITION_LISTENINGS NUMBER 
, TRACK_COMMENT VARCHAR2(300) 
, CURRENT_LISTENING CHAR(1) 
, PAUSE_TIME NUMBER 
);


INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Владислав', 'Кисляков', 'Chewbaca', 'ChewbacaMorning@gmail.com', 'Morning', 'User', 'Electronic', 'Nicolas Jaar - El Bandido', 6.37, 'Oleg', 'Synytsky', 'Dreamboat', 'yes', 2126, 108000, 'Nah not feelin it', NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Владислав', 'Кисляков', 'Chewbaca', 'ChewbacaMorning@gmail.com', 'Morning', 'User', 'Electronic', 'Electro - Trance - House', 4.09, 'Oleg', 'Synytsky', 'Dreamboat', 'no', 4005, 5055, NULL, NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Владислав', 'Кисляков', 'Chewbaca', 'ChewbacaMorning@gmail.com', 'Morning', 'User', 'Electronic', 'Nice Night', 5.21, 'Oleg', 'Synytsky', 'Dreamboat', 'yes', 88, 82000, 'NIGGER!!!!', 'Y', 1.02);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Владислав', 'Кисляков', 'Chewbaca', 'ChewbacaMorning@gmail.com', 'Morning', 'User', 'Electronic', 'Electro 2020', 10.05, 'Christian', 'Radaelli', 'Dumpling', 'no', 231, 99548, 'Sadie is my dog', NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Владислав', 'Кисляков', 'Chewbaca', 'ChewbacaMorning@gmail.com', 'Morning', 'User', 'Electronic', 'REMIX BOLICHEROS 2019!!!', 8.01, 'Christian', 'Radaelli', 'Dumpling', 'yes', 84, 32001, NULL, NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Елизавета', 'Рапинчук', 'Bug', 'Circle_Bug@gmail.com', 'Sport', 'System', 'Sport', 'Drifting', 2.11, 'Ten', 'Walls', 'Monsieur', 'no', 34, 806, 'Jesus christ', NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Елизавета', 'Рапинчук', 'Bug', 'Circle_Bug@gmail.com', 'Sport', 'System', 'Sport', 'SESSION #186 (Feat. Ten Walls)', 4.02, 'Ten', 'Walls', 'Monsieur', 'yes', 456, 1050, NULL, NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Елизавета', 'Рапинчук', 'Bug', 'Circle_Bug@gmail.com', 'Sport', 'System', 'Pop', 'Ariana Grande - Side To Side Ft. Nicki Minaj (Remix)', 3.12, 'Kelvin ', 'Pasman', 'Snuggy', 'no', 1102, 1526, 'another classic', NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Елизавета', 'Рапинчук', 'Bug', 'Circle_Bug@gmail.com', 'Sport', 'System', 'Pop', 'Major Lazer - Too Original (Remix)', 2.45, 'Kelvin ', 'Pasman', 'Snuggy', 'yes', 358, 1200, 'адский разгон', NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Елизавета', 'Рапинчук', 'Bug', 'Circle_Bug@gmail.com', 'Sport', 'System', 'Sport', 'Ten Walls - Sparta', 3.44, 'Ten', 'Walls', 'Monsieur', 'no', 88, 22000, 'Очень серьезный кач', 'Y', 2.01);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Елизавета', 'Рапинчук', 'Bug', 'Circle_Bug@gmail.com', 'Bamboo', 'User', 'Chill', 'Murda On They Mind (Tales From Mount Zion)', 3.02, 'Den', 'Philips', 'DJ Bishop', 'yes', 3306, 540050, NULL, NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Елизавета', 'Рапинчук', 'Bug', 'Circle_Bug@gmail.com', 'Bamboo', 'User', 'Electronic', 'James Blake - Air & Lack Thereof', 4.09, 'H?lder', 'Leal', 'Hotshot', 'no', 4455, 1433, NULL, NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Елизавета', 'Рапинчук', 'Bug', 'Circle_Bug@gmail.com', 'Bamboo', 'User', 'Electronic', 'Little Fish', 2.13, 'H?lder', 'Leal', 'Hotshot', 'yes', 6587, 8890, NULL, NULL, NULL);

INSERT INTO DATA_TABLE (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, GENRE, COMPOSITION_NAME, DURATION, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKED, COMPOSITION_LIKES, COMPOSITION_LISTENINGS, TRACK_COMMENT, CURRENT_LISTENING, PAUSE_TIME) 
VALUES ('Елизавета', 'Рапинчук', 'Bug', 'Circle_Bug@gmail.com', 'Bamboo', 'User', 'Electronic', 'Jamie XX - Loud Places (feat. Romy)', 4.43, 'H?lder', 'Leal', 'Hotshot', 'no', 2201, 202023, NULL, NULL, NULL);
