DEFINE USER_NAME = &&1
DEFINE DATA_TABLESPACE = '&&USER_NAME._DATA'
DEFINE INDEX_TABLESPACE = '&&USER_NAME._INDEX'



ALTER TABLE USERS ADD CONSTRAINT PK_USER PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE ALBUM ADD CONSTRAINT PK_ALBUM PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE ALBUM_REVIEW ADD CONSTRAINT PK_ALBUM_REVIEW PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE COMPOSITION ADD CONSTRAINT PK_COMPOSITION PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE COMPOSITION_OWNER ADD CONSTRAINT PK_COMPOSITION_OWNER PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE COMPOSITION_REVIEW ADD CONSTRAINT PK_COMPOSITION_REVIEW PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE GENRE ADD CONSTRAINT PK_GENRE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE LISTENING_HISTORY ADD CONSTRAINT PK_LISTENING_HISTORY PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE PLAYLIST ADD CONSTRAINT PK_PLAYLIST PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE PLAYLIST_CONTENT ADD CONSTRAINT PK_PLAYLIST_CONTENT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE USER_PLAYLIST ADD CONSTRAINT PK_USER_PLAYLIST PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE USER_STATE ADD CONSTRAINT PK_USER_STATE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;






ALTER TABLE USER_STATE ADD CONSTRAINT FK_USER_STATE_USER FOREIGN KEY(USER_ID)
REFERENCES USERS(ID) ON DELETE SET NULL;

CREATE INDEX FK_USER_STATE_USER ON USER_STATE(USER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE USER_STATE ADD CONSTRAINT FK_USER_STATE_COMPOSITION FOREIGN KEY(COMPOSITION_ID)
REFERENCES COMPOSITION(ID) ON DELETE SET NULL;

CREATE INDEX FK_USER_STATE_COMPOSITION ON USER_STATE(COMPOSITION_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE USER_STATE ADD CONSTRAINT FK_USER_STATE_ALBUM FOREIGN KEY(ALBUM_ID)
REFERENCES ALBUM(ID) ON DELETE SET NULL;

CREATE INDEX FK_USER_STATE_ALBUM ON USER_STATE(ALBUM_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE ALBUM_REVIEW ADD CONSTRAINT FK_ALBUM_REVIEW_USER FOREIGN KEY(USER_ID)
REFERENCES USERS(ID) ON DELETE SET NULL;

CREATE INDEX FK_ALBUM_REVIEW_USER ON ALBUM_REVIEW(USER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE ALBUM_REVIEW ADD CONSTRAINT FK_ALBUM_REVIEW_ALBUM FOREIGN KEY(ALBUM_ID)
REFERENCES ALBUM(ID) ON DELETE SET NULL;

CREATE INDEX FK_ALBUM_REVIEW_ALBUM ON ALBUM_REVIEW(ALBUM_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE COMPOSITION_REVIEW ADD CONSTRAINT FK_COMPOSITION_REVIEW_USER FOREIGN KEY(USER_ID)
REFERENCES USERS(ID) ON DELETE SET NULL;

CREATE INDEX FK_COMPOSITION_REVIEW_USER ON COMPOSITION_REVIEW(USER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE COMPOSITION_REVIEW ADD CONSTRAINT FK_COMPOSITION_REVIEW_COMPOSITION FOREIGN KEY(COMPOSITION_ID)
REFERENCES COMPOSITION(ID) ON DELETE SET NULL;

CREATE INDEX FK_COMPOSITION_REVIEW_COMPOSITION ON COMPOSITION_REVIEW(COMPOSITION_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE PLAYLIST_CONTENT ADD CONSTRAINT FK_PLAYLIST_CONTENT_COMPOSITION FOREIGN KEY(COMPOSITION_ID)
REFERENCES COMPOSITION(ID) ON DELETE SET NULL;

CREATE INDEX FK_PLAYLIST_CONTENT_COMPOSITION ON PLAYLIST_CONTENT(COMPOSITION_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE PLAYLIST_CONTENT ADD CONSTRAINT FK_PLAYLIST_CONTENT_ALBUM FOREIGN KEY(ALBUM_ID)
REFERENCES ALBUM(ID) ON DELETE SET NULL;

CREATE INDEX FK_PLAYLIST_CONTENT_ALBUM ON PLAYLIST_CONTENT(ALBUM_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE PLAYLIST_CONTENT ADD CONSTRAINT FK_PLAYLIST_CONTENT_PLAYLIST FOREIGN KEY(PLAYLIST_ID)
REFERENCES PLAYLIST(ID) ON DELETE SET NULL;

CREATE INDEX FK_PLAYLIST_CONTENT_PLAYLIST ON PLAYLIST_CONTENT(PLAYLIST_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE COMPOSITION ADD CONSTRAINT FK_COMPOSITION_ALBUM FOREIGN KEY(ALBUM_ID)
REFERENCES ALBUM(ID) ON DELETE SET NULL;

CREATE INDEX FK_COMPOSITION_ALBUM ON COMPOSITION(ALBUM_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE COMPOSITION ADD CONSTRAINT FK_COMPOSITION_OWNER FOREIGN KEY(OWNER_ID)
REFERENCES COMPOSITION_OWNER(ID) ON DELETE SET NULL;

CREATE INDEX FK_COMPOSITION_OWNER ON COMPOSITION(OWNER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE LISTENING_HISTORY ADD CONSTRAINT FK_LISTENING_HISTORY_ALBUM FOREIGN KEY(ALBUM_ID)
REFERENCES ALBUM(ID) ON DELETE SET NULL;

CREATE INDEX FK_LISTENING_HISTORY_ALBUM ON LISTENING_HISTORY(ALBUM_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE LISTENING_HISTORY ADD CONSTRAINT FK_LISTENING_HISTORY_COMPOSITION FOREIGN KEY(COMPOSITION_ID)
REFERENCES COMPOSITION(ID) ON DELETE SET NULL;

CREATE INDEX FK_LISTENING_HISTORY_COMPOSITION ON LISTENING_HISTORY(COMPOSITION_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE LISTENING_HISTORY ADD CONSTRAINT FK_LISTENING_HISTORY_USER FOREIGN KEY(USER_ID)
REFERENCES USERS(ID) ON DELETE SET NULL;

CREATE INDEX FK_LISTENING_HISTORY_USER ON LISTENING_HISTORY(USER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE GENRE ADD CONSTRAINT FK_GENRE_COMPOSITION FOREIGN KEY(COMPOSITION_ID)
REFERENCES COMPOSITION(ID) ON DELETE SET NULL;

CREATE INDEX FK_GENRE_COMPOSITION ON GENRE(COMPOSITION_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE USER_PLAYLIST ADD CONSTRAINT FK_USER_PLAYLIST_USER FOREIGN KEY(USER_ID)
REFERENCES USERS(ID) ON DELETE SET NULL;

CREATE INDEX FK_USER_PLAYLIST_USER ON USER_PLAYLIST(USER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE USER_PLAYLIST ADD CONSTRAINT FK_USER_PLAYLIST_PLAYLIST FOREIGN KEY(PLAYLIST_ID)
REFERENCES PLAYLIST(ID) ON DELETE SET NULL;

CREATE INDEX FK_USER_PLAYLIST_PLAYLIST ON USER_PLAYLIST(PLAYLIST_ID) TABLESPACE &&INDEX_TABLESPACE;