DEFINE USER_NAME = &&1
DEFINE DATA_TBS = '&&USER_NAME._DATA'

CREATE TABLE COMPOSITION (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	COMPOSITION_NAME VARCHAR2(100) NOT NULL,
	DURATION NUMBER NOT NULL,
	LIKES_NUMBER NUMBER,
	LISTENINGS_NUMBER NUMBER,
	RATING NUMBER,
	ALBUM_ID NUMBER,
	OWNER_ID NUMBER
)
TABLESPACE &&DATA_TBS;