DEFINE USER_NAME = &&1
DEFINE DATA_TBS = '&&USER_NAME._DATA'

CREATE TABLE LISTENING_HISTORY (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	COMPOSITION_ID NUMBER NOT NULL,
	ALBUM_ID NUMBER,
	USER_ID NUMBER NOT NULL,
	LISTENING_DATE DATE NOT NULL
)
TABLESPACE &&DATA_TBS;