CREATE TABLE USERS (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	FIRST_NAME VARCHAR2(100) NOT NULL,
	LAST_NAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	NICKNAME VARCHAR2(200) NOT NULL
);