CREATE TABLE PLAYLIST_CONTENT (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	PLAYLIST_ID NUMBER NOT NULL,
	COMPOSITION_ID NUMBER NOT NULL,
	ALBUM_ID NUMBER
);