DEFINE USER_NAME = &&1
DEFINE DATA_TBS = '&&USER_NAME._DATA'

CREATE TABLE USER_STATE (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	USER_ID NUMBER NOT NULL,
	COMPOSITION_ID NUMBER,
	ALBUM_ID NUMBER,
	CURRENT_COMPOSITION VARCHAR2(100),
	CURRENT_ALBUM VARCHAR(100),
	PAUSE_TIME NUMBER
)
TABLESPACE &&DATA_TBS;