CREATE TABLE LISTENING_HISTORY (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	ID_COMPOSITION NUMBER NOT NULL,
	ID_ALBUM NUMBER,
	ID_USER NUMBER NOT NULL,
	LISTENING_DATE DATE NOT NULL
);