CREATE TABLE COMPOSITION_OWNER (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	FIRST_NAME VARCHAR2(100),
	LAST_NAME VARCHAR2(100),
	NICKNAME VARCHAR2(100) NOT NULL
);